// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9X_JqAksddth3_mXzmDYmibb_6kEC3T8',
    appId: '1:788735896694:web:0b21ff61f57960c7448357',
    messagingSenderId: '788735896694',
    projectId: 'rakshak-5',
    authDomain: 'rakshak-5.firebaseapp.com',
    storageBucket: 'rakshak-5.firebasestorage.app',
    measurementId: 'G-JYWRPE829E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsag2_ts8jPYzFSQHQzz-l0u69zmCr_0Q',
    appId: '1:788735896694:android:9fa20df519e63ed2448357',
    messagingSenderId: '788735896694',
    projectId: 'rakshak-5',
    storageBucket: 'rakshak-5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUqrvfwMgPnNBY7XjMjO57qjN-TLLGqw',
    appId: '1:788735896694:ios:ede6ea1c00efb775448357',
    messagingSenderId: '788735896694',
    projectId: 'rakshak-5',
    storageBucket: 'rakshak-5.firebasestorage.app',
    iosBundleId: 'com.rakshak.rakshak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvUqrvfwMgPnNBY7XjMjO57qjN-TLLGqw',
    appId: '1:788735896694:ios:ede6ea1c00efb775448357',
    messagingSenderId: '788735896694',
    projectId: 'rakshak-5',
    storageBucket: 'rakshak-5.firebasestorage.app',
    iosBundleId: 'com.rakshak.rakshak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9X_JqAksddth3_mXzmDYmibb_6kEC3T8',
    appId: '1:788735896694:web:25ffbb2eac0d9579448357',
    messagingSenderId: '788735896694',
    projectId: 'rakshak-5',
    authDomain: 'rakshak-5.firebaseapp.com',
    storageBucket: 'rakshak-5.firebasestorage.app',
    measurementId: 'G-EHBP5M5ZK5',
  );
}
